### ISSUE TITLE
Wiki needed for backend and frontend routes.

### ISSUE THREAD

**Issue by ConleyPotter** [ConleyPotter/getsy#13]
I think we should take some time this morning, to discuss what our routes look like so far and where we want the rest of them to go. We could create a wiki for it just like we did for our full-stack projects.

**Comment by lhsteele** [comment]
Backend Routes and Frontend Routes wiki done. 
Realized we don't have backend routes written yet for product deletion and edit.

**Comment by ConleyPotter** [comment]
All done! Also added a state shape wiki.
